<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getFeeAmount()): ?>
    <tr>
        <?php $method = $this->getOrder()->getPayment()->getMethod(); ?>
        <?php $title  = Mage::getModel('payment_fee/fee')->getTotalTitle($method); ?>
        <td class="label"><?php echo $title; ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseFeeAmount(), $this->getSource()->getFeeAmount()); ?>
        </td>
    </tr>
<?php endif; ?>